config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :questions

  resources :question_types

  resources :question_options

  resources :answers do
  member do
    get "vote"
  end
end

  resources :resumes do
  member do
    get "vote"
  end
end

  resources :educations

  resources :experiences

  resources :roles

  resources :schools

  resources :companies

  resources :references

  resources :addresses

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :references
  has_many :schools
  has_many :companies
  has_many :users
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :resume
  belongs_to :user
  acts_as_votable 
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :address
  has_many :experiences
  has_many :references
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :resume
  belongs_to :user
  belongs_to :school
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :role
  belongs_to :company
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :question_type
  has_many :question_options
  has_many :answers
end

app/models/question_option.rb
class QuestionOption < ActiveRecord::Base
  belongs_to :question
end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
  has_many :questions
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  belongs_to :company
  belongs_to :address
  belongs_to :education
  belongs_to :role
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  acts_as_votable 
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :references
  has_many :experiences
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :address
  has_many :educations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_many :resumes
  has_many :answers
  belongs_to :address
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first

    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)
    @education.user = current_user

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:resume_id, :user_id, :education_name, :finished_with_certificate, :startdate, :enddate, :school_id, :description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/educations/_form.html.erb
<%= form_for @education, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :education_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :education_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :finished_with_certificate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :finished_with_certificate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :startdate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :startdate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :enddate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :enddate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  educations_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/educations/edit.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Education %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/index.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => Education %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:education_name) %></th>
      <th><%= model_class.human_attribute_name(:finished_with_certificate) %></th>
      <th><%= model_class.human_attribute_name(:startdate) %></th>
      <th><%= model_class.human_attribute_name(:enddate) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.id %></td>
        <td><%= education.education_name %></td>
        <td><%= education.finished_with_certificate %></td>
        <td><%= education.startdate %></td>
        <td><%= education.enddate %></td>
        <td><%= education.description %></td>
        <td><%=l education.created_at, format: :long %></td>
        <td>
          <%= link_to education_path(education), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to education_path(education), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_education_path,
            :class => 'btn btn-primary' %>

app/views/educations/new.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Education %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/show.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => Education %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:education_name) %></dt>
      <dd><pre class="prettyprint"><%= @education.education_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:finished_with_certificate) %></dt>
      <dd><pre class="prettyprint"><%= @education.finished_with_certificate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:startdate) %></dt>
      <dd><pre class="prettyprint"><%= @education.startdate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:enddate) %></dt>
      <dd><pre class="prettyprint"><%= @education.enddate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @education.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              educations_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_education_path(@education), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              education_path(@education),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>